import { Inconsolata } from "next/font/google";
import "./globals.css";

const InconsolataFont = Inconsolata({ subsets: ["latin"] });

export const metadata = {
  title: "Travel blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={InconsolataFont.className}>{children}</body>
    </html>
  );
}
